services:
  postgres:
    image: postgres:16-alpine
    container_name: jsonview-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: jsonview-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_URL: ${CLIENT_URL}
    ports:
      - "8080:${SERVER_PORT}"

volumes:
  postgres-data:
    driver: local